version: 2
jobs:
  build:
    docker:
      - image: ubuntu:18.04

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/work

    steps:
      - run: apt-get update
      - run: apt-get install -y git python3-h5py python3-pip python3-dev libopenblas-dev
      - checkout
      - run: python3 setup.py install
      - run: python3 setup.py test
